[package]
name = "telgen"
version = "0.1.0"
authors = ["Rafi Mueen <r.mueen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.27.0"
chrono = "0.4"
whoami = "1.1.1"
